### ISSUE TITLE
Accent Not Supported

### ISSUE THREAD

**Issue by Jinil-JP** [douglashill/KeyboardKit#15] opened 2021-01-06 14:27 UTC
I Already implemented the keyboard Kit but not found a way to add Accent for characters they are not providing this type of functionality.

**Comment by douglashill** [comment] 2021-01-07 09:31
I’m sorry but I don’t understand what the issue is. Please can you explain more:

- What you’re trying to achieve
- What you tried so far

It might help make the issue clearer if you can include a screenshot.

**Comment by douglashill** [comment] 2021-01-28 18:56
I didn’t hear back so I’m closing this issue, but please follow up if you provide more details about the problem.

**Closed as completed by douglashill** 2021-01-28 18:56 UTC
